name: Build (no push)
on:
  pull_request:
  push:
    branches-ignore: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: docker build -f src/Bracketly.WebApp/Dockerfile -t bracketly:test .
      - run: docker run -d -p 8080:8080 bracketly:test && sleep 10 && curl -f http://localhost:8080
