name: Push to GHCR
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  IMAGE_NAME: bracketly-webapp

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Bracketly.WebApp/Dockerfile
          push: true
          tags: |
            ghcr.io/constantinprog/${{ env.IMAGE_NAME }}:latest
            ghcr.io/constantinprog/${{ env.IMAGE_NAME }}:${{ github.sha }}
